Remove unused Python pip cache as it breaks tests
https://github.com/mbrukman/cloud-launcher/actions/runs/16582681299/job/46901919689

> Post Set up Python
>
> Post job cleanup.
> Error: Cache folder path is retrieved for pip but doesn't exist on disk:
> /home/runner/.cache/pip. This likely indicates that there are no dependencies
> to cache. Consider removing the cache step if it is not needed.